# Generated by Django 3.2.9 on 2021-12-13 10:41

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('photo', models.ImageField(upload_to='author/')),
                ('about', models.TextField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Author Profile',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rblog.authorprofile')),
            ],
            options={
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(upload_to='product/')),
                ('created_date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rblog.authorprofile')),
            ],
            options={
                'verbose_name_plural': 'Blog Category',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50, null=True)),
                ('blog_image', models.ImageField(upload_to='product/')),
                ('blog_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('pub_date', models.DateField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_date', models.DateField(auto_now=True)),
                ('blog_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rblog.authorprofile')),
                ('blog_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rblog.blogcategory')),
                ('blog_tag', models.ManyToManyField(to='rblog.Tag')),
            ],
            options={
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
