# Generated by Django 3.2.9 on 2021-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_video_link',
            field=models.FileField(upload_to=''),
        ),
    ]
