# Generated by Django 3.2.9 on 2021-12-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertiesimages',
            name='builder_name',
        ),
    ]
