# Generated by Django 3.2.9 on 2021-12-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rportal', '0002_alter_aboutus_about_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='bank_name')),
                ('video_name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Banner Video',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_operationer',
        ),
    ]
