# Generated by Django 3.2.9 on 2021-12-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rportal', '0002_remove_propertiesimages_builder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='contact_page_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='home_page_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
